trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

pool:
  name: VSEng-MicroBuildVS2019
  demands: 
    - msbuild

steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Unsigned Artifacts'
    inputs:
      project: $(System.TeamProjectId)
      pipeline: $(System.DefinitionId)
      buildId: 4057966
      downloadPath: $(Build.StagingDirectory)
      artifactName: nuget
      buildType: specific
      buildVersionToDownload: specific
      downloadType: single

  - task: MicroBuildSigningPlugin@2
    displayName: 'Prepare Signing Tools'
    inputs:
      signType: 'Real'
    env:
      TeamName: 'Xamarin'

  - task: MicroBuildCodesignVerify@2
    inputs:
      TargetFolders: '$(Build.StagingDirectory)'

  - task: MicroBuildCleanup@1
    displayName: 'Clean Up Signing Tools'
    env:
      TeamName: 'Xamarin'