trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

pool:
  name: VSEng-MicroBuildVS2019
  demands: 
    - msbuild

steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Unsigned Artifacts'
    inputs:
      project: $(System.TeamProjectId)
      pipeline: $(System.DefinitionId)
      buildId: 4037101
      downloadPath: $(Build.StagingDirectory)
      artifactName: nuget
      buildType: specific
      buildVersionToDownload: specific
      downloadType: single

  - powershell: |
      New-Item "$(Build.StagingDirectory)" -ItemType Directory -Force | Out-Null
      $downloader = New-Object System.Net.WebClient
      $downloader.Headers["Authorization"] = 'token $(Github.Token)'
      $downloader.DownloadFile(
        "https://raw.githubusercontent.com/xamarin/yaml-templates/main/sign-artifacts/steps/v2-ExtractNupkgs.ps1",
        "$(Build.StagingDirectory)\ExtractNupkgs.ps1")
    displayName: 'Download Signing Scripts'
  - powershell: '.\ExtractNupkgs.ps1 -SourceDir "$(Build.StagingDirectory)" -DestinationDir "$(Build.StagingDirectory)\extracted"'
    workingDirectory: '$(Build.StagingDirectory)'
    displayName: 'Extract NuGet Packages'

  - task: MicroBuildSigningPlugin@2
    displayName: 'Prepare Signing Tools'
    inputs:
      signType: 'Real'
    env:
      TeamName: 'Xamarin'

  - task: MicroBuildCodesignVerify@2
    inputs:
      TargetFolders: '$(Build.StagingDirectory)\extracted'
      ExcludeSNVerify: true

  - task: MicroBuildCleanup@1
    displayName: 'Clean Up Signing Tools'
    env:
      TeamName: 'Xamarin'